### ISSUE TITLE
Possible race condition when retrieving tables after deletion

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#347]
I discovered this when adding things to the client side, where one of the operations is to delete a table, and then immediately query for node tables. I've gotten two distinct errors from this, but they seem to stem from the same general premise.

Couple of stack traces for reference (I've annotated where the stack trace goes from our code to arango) :
```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 251, in __iter__
    reraise(*_capture_exception(self._hub))
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 247, in __iter__
    chunk = next(iterator)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/jake/projects/multinet-server/multinet/util.py", line 69, in generate
    for row in iterator:
  File "/home/jake/projects/multinet-server/multinet/db.py", line 228, in <genexpr>
    return (table[0] for table in tables if desired_type(table))
  File "/home/jake/projects/multinet-server/multinet/db.py", line 207, in <genexpr>
    if not table["name"].startswith("_")
  File "/home/jake/projects/multinet-server/multinet/db.py", line 362, in table_fields
    if space.has_collection(table) and space.collection(table).count() > 0:
--------------------------------------------------------------------------------------------
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/collection.py", line 554, in count
    return self._execute(request, response_handler)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/executor.py", line 81, in execute
    return response_handler(response)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/collection.py", line 549, in response_handler
    raise DocumentCountError(resp, request)
arango.exceptions.DocumentCountError: [HTTP 404][ERR 1203] collection or view not found
```

```
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 251, in __iter__
    reraise(*_capture_exception(self._hub))
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    raise value
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/sentry_sdk/integrations/wsgi.py", line 247, in __iter__
    chunk = next(iterator)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/jake/projects/multinet-server/multinet/util.py", line 69, in generate
    for row in iterator:
  File "/home/jake/projects/multinet-server/multinet/db.py", line 228, in <genexpr>
    return (table[0] for table in tables if desired_type(table))
  File "/home/jake/projects/multinet-server/multinet/db.py", line 207, in <genexpr>
    if not table["name"].startswith("_")
  File "/home/jake/projects/multinet-server/multinet/db.py", line 363, in table_fields
    sample = space.collection(table).random()
--------------------------------------------------------------------------------------------
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/collection.py", line 1186, in random
    return self._execute(request, response_handler)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/api.py", line 58, in _execute
    return self._executor.execute(request, response_handler)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/executor.py", line 81, in execute
    return response_handler(response)
  File "/home/jake/.local/share/virtualenvs/multinet-server-he5vy4Rf/lib/python3.7/site-packages/arango/collection.py", line 1181, in response_handler
    raise DocumentGetError(resp, request)
arango.exceptions.DocumentGetError: [HTTP 404][ERR 1203] unknown collection 'miserables2_nodes'
```

Of the two errors above, I've observed the former more frequently than the latter.

On the frontend, this error results in a response payload of just `[` from the endpoint:

```
GET /api/workspaces/<workspace>/tables?type=node
```

Which results in the workspace listing of tables to look like this:

![Screenshot from 2020-03-18 19-23-58](https://user-images.githubusercontent.com/11370025/77016474-1c37b580-694e-11ea-9fff-f8a05ec17174.png)

This doesn't happen consistently for me, and the only way I know how to reproduce it is to repeatedly upload and delete tables until it happens (I've only tested with node tables specifically).

Please let me know if anyone is able to successfully reproduce this error.

**Comment by waxlamp** [comment]
This is wild.

You can get that error just from repeatedly uploading and downloading the same table? How fast do you have to do it?

Do you have any inkling where that `[` comes from? The name of the one table getting split into one-letter chunks is familiar to me--it often results in Python from expecting an array of strings but only getting a string (which really *is*, in the duck typing sense, an array of strings--don't get me started on this).

And just for background: what were you doing/working on that led you to find this bug?

**Comment by AlmightyYakob** [comment]
> You can get that error just from repeatedly uploading and downloading the same table? How fast do you have to do it?

Not necessarily the same table, but just deleting a table, as the client immediately makes calls to the arangodb instance. I don't think it's a matter of speed, it's more luck of the draw (at least for me).

> Do you have any inkling where that `[` comes from? 

It comes from the generate function:

https://github.com/multinet-app/multinet-server/blob/682cfebeb1a6a5860b47be7e6bee5839899378f6/multinet/util.py#L64-L73

I'm pretty sure what's happening is that since we're generating/streaming the JSON response, the first `[` gets sent, and then once the generator is called to receive the first item, it errors out, resulting in just the `[` having been sent.


> And just for background: what were you doing/working on that led you to find this bug?

I was trying to add `vuex` experimentally to see how well it worked. But again, I've tested this on master as well. I wouldn't be surprised if this was hard/impossible to reproduce from you guys, it seems like it could just be a quirk of my specific system, since I've never run into this until now.

**Comment by waxlamp** [comment]
> > Do you have any inkling where that `[` comes from?
> 
> It comes from the generate function:
> 
> https://github.com/multinet-app/multinet-server/blob/682cfebeb1a6a5860b47be7e6bee5839899378f6/multinet/util.py#L64-L73
> 
> I'm pretty sure what's happening is that since we're generating/streaming the JSON response, the first `[` gets sent, and then once the generator is called to receive the first item, it errors out, resulting in just the `[` having been sent.
> 

Ah I've always felt weird about that generator function.

Do you know what could be causing it to error out? I am not super expert in Python generators, unfortunately.

**Comment by AlmightyYakob** [comment]
I actually don't think this is a problem with the generator function, but rather with how operate arango. I was thinking about this a bit, and I think this may be in part due to the new workspace mapping feature. That extra time that takes could be allowing this race condition to get off the ground, but I'm not certain. I'll have to look into it more.

**Comment by waxlamp** [comment]
> I actually don't think this is a problem with the generator function, but rather with how we operate arango. I was thinking about this a bit, and I think this may be in part due to the new workspace mapping feature. That extra time that takes could be allowing this race condition to get off the ground, but I'm not certain. I'll have to look into it more.

Oh gotcha. I'll leave this one to you then. Thanks @AlmightyYakob.
